Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.define :debian12 do |debian|
        debian.vm.box = 'debian/bookworm64'
    end

    config.vm.define :ubuntu2404 do |ubuntu|
        ubuntu.vm.box = 'bento/ubuntu-24.04'
    end

    config.vm.define :fedora41 do |fedora|
        fedora.vm.box = 'bento/fedora-41'
    end

    config.vm.define :almalinux9 do |almalinux|
        almalinux.vm.box = 'almalinux/9'
    end
end
